### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Gon1976** [MrTomRod/flower-plot#1]
Hi, I am trying to install using pip and I have two error (first I try with pip but i think is linked to old version of python), then I update python3 to python3.11 and I use pip3, but I have a second error:
pip install git+https://github.com/MrTomRod/flower-plot.git
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/MrTomRod/flower-plot.git
  Cloning https://github.com/MrTomRod/flower-plot.git to /tmp/pip-req-build-Jh1Yhd
  Running command git clone -q https://github.com/MrTomRod/flower-plot.git /tmp/pip-req-build-Jh1Yhd
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-Jh1Yhd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-Jh1Yhd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-CIQG_L
         cwd: /tmp/pip-req-build-Jh1Yhd/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-Jh1Yhd/setup.py", line 2, in <module>
        import pathlib
    ImportError: No module named pathlib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ggreif@UBM12:~$ pip3 install git+https://github.com/MrTomRod/flower-plot.git
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
           ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'

can you helpme?
thanks

**Comment by MrTomRod** [comment]
Hey :)

The first error is indeed caused by Python 2.7.

The second probably relates to the missing library distutils. I thought this was normally preinstalled on most systems, but apparently not. Run `apt-get install python3-distutils` (or something like this) and try again.

Hint: consider using GitHub markdown to improve the readability of your issues: [Link](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by Gon1976** [comment]
solved with: python3.8 -m pip install git+https://github.com/MrTomRod/flower-plot.git
