### ISSUE TITLE
error with example 

### ISSUE THREAD

**Issue by Gon1976** [MrTomRod/flower-plot#2]
After successfully installed y tried the package.
As i understand i make the example as an python script (flower.py) and run with the python version I installed flower_plot but I get the error TypeError: 'type' object is not subscriptable, see below:
ggreif@UBM12:~$ cat > flower.py
# some data:
genome_to_data = {
    'FakeGenome0': {'color': (0.500, 0.000, 1.000), 'shell': 48, 'unique': 0},
    'FakeGenome1': {'color': (0.452, 0.073, 0.999), 'shell': 53, 'unique': 4},
    'FakeGenome2': {'color': (0.398, 0.159, 0.996), 'shell': 95, 'unique': 0}
}

import matplotlib.pyplot as plt
from flower_plot import flower_plot

flower_plot(genome_to_data=genome_to_data, n_core=788)
plt.tight_layout()
plt.show()
^C
ggreif@UBM12:~$ python3.8 flower.py
Traceback (most recent call last):
  File "flower.py", line 9, in <module>
    from flower_plot import flower_plot
  File "/home/ggreif/.local/lib/python3.8/site-packages/flower_plot/__init__.py", line 4, in <module>
    from .flower_plot import flower_plot
  File "/home/ggreif/.local/lib/python3.8/site-packages/flower_plot/flower_plot.py", line 35, in <module>
    genome_to_data: dict[str:dict],
TypeError: 'type' object is not subscriptable

**Comment by MrTomRod** [comment]
The problem is that you're using Python 3.8. This library uses Python 3.9 features such as type hinting, which are not supported by previous versions. Please use Python 3.9 or higher.
